pt:
  THEME_ROSAZ:
    BRAND: 'Instituto Beato Rosaz'
    HERO:
      TITLE: 'Um título bonito aqui (PT)'
      SUBTITLE: 'Um subtítulo inspirador para resumir a missão do instituto (PT).'
      BUTTON: 'Saiba mais'

it:
  THEME_ROSAZ:
    BRAND: 'Istituto Beato Rosaz'
    HERO:
      TITLE: 'Un bel titolo qui (IT)'
      SUBTITLE: 'Un sottotitolo ispiratore per riassumere la missione dell’istituto (IT).'
      BUTTON: 'Scopri di più'
